Configuracion de prod 9 - configurando redis

diff --git a/backend/compose/production/django/entrypoint b/backend/compose/production/django/entrypoint
--- a/backend/compose/production/django/entrypoint
+++ b/backend/compose/production/django/entrypoint
@@ -14,4 +14,14 @@ wait-for-it "${POSTGRES_HOST}:${POSTGRES_PORT}" -t 30
 
 >&2 echo 'PostgreSQL is available'
 
+if [ -z "${REDIS_URL}" ]; then
+  >&2 echo 'Error: REDIS_URL is not set'
+  exit 1
+fi
+
+redis_host_port=$(echo "${REDIS_URL}" | sed -E 's/redis:\/\/([^:]+):([0-9]+)/\1:\2/')
+wait-for-it "${redis_host_port}" -t 30
+
+>&2 echo 'Redis is available'
+
 exec "$@"
